<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVRTMnf2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVRTMnf2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVRTMnf2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVRTMnf2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVRTMnf2\App_KernelDevDebugContainer([
    'container.build_hash' => 'VRTMnf2',
    'container.build_id' => '4b2b6a48',
    'container.build_time' => 1594897860,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVRTMnf2');
