<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCGngtIY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCGngtIY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCGngtIY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCGngtIY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCGngtIY\App_KernelDevDebugContainer([
    'container.build_hash' => 'CGngtIY',
    'container.build_id' => '0c28ce55',
    'container.build_time' => 1591368554,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCGngtIY');
