<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB9K7s1o\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB9K7s1o/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB9K7s1o.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB9K7s1o\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB9K7s1o\App_KernelDevDebugContainer([
    'container.build_hash' => 'B9K7s1o',
    'container.build_id' => '57c71d1d',
    'container.build_time' => 1594908277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB9K7s1o');
